### ISSUE TITLE
Echo Error Handler

### ISSUE THREAD

**Issue by 1995parham** [mschneider82/problem#2]
Do you think to implement an error handler for [Echo](https://github.com/labstack/echo) that can handle the Problem instances in this repository, is a good idea?

**Comment by mschneider82** [comment]
I have never used echo, but looking in the godoc you can already use problem.WirteTo to a echo.Response

I will try it tomorrow and may add an example to the readme.

**Comment by 1995parham** [comment]
Echo has `ErrorHandler` that can handle go errors. I think we can use it and if the given error is Problem then return it with standard problem response. I can create PR if you agree.

**Comment by mschneider82** [comment]
You can create a pr so i can see what you mean. But adding echo as dependency is too much for this small package. Maybe just add a snippet to readme

**Comment by 1995parham** [comment]
I have created a [gist](https://gist.github.com/1995parham/456da5a759597124cf1f87c0ce6b6031). If you agree we can add it as an example for the Echo framework.

**Comment by mschneider82** [comment]
thanks, now i have a clue about `echo`. it seems that every Handler replies an `error`, even if it is just a c.String. Since `problem` is an `error`, we can simple reply it. The custom `ErrorHandler` is needed to reply the correct statuscode and message.

If you want to publish your gist with used MIT license, please create a pull request for the README.md

**Comment by 1995parham** [comment]
@mschneider82 exactly. I will create a PR for README.md. Thanks for your time.
